version: "3"

services:
  wog-web:
    build: .
    image: wog-web
    ports:
      - "8081:8081"
    container_name: wog-web

#services:
#  wog-web:
#    image: wogweb
#    restart: always
#    ports:
#      - "8081:8081"
#    volumes:
#      - ".:/app:rw"
#
#  wog:
#    image: wog
#    restart: always
#    volumes:
#      - ".:/app"