version: "3"

services:
  wog-web:
    image: mosheb3/wog-web
    restart: unless-stoped
    volumes:
      - "./data:/app/data:ro"
    ports:
      - "8081:8081"
    container_name: wog-web
    #entrypoint: ["python3 /app/webServer.py"]
  wog:
    image: mosheb3/wog
    volumes:
      - "./data:/app/data:rw"
    container_name: wog
    #entrypoint: ["/app/runGame.sh"]
