version: "3"

services:
  wog-web:
    image: mosheb3/wog-web
    restart: always
    volumes:
      - "./logs:/app/logs:ro"
      - "./data:/app/data:ro"
    ports:
      - "8081:8081"
    container_name: wog-web
  wog:
    image: mosheb3/wog
    depends_on:
      - wog-web
    container_name: wog
